{% set version = "1.3" %}

package:
  name: otlhs
  version: {{ version }}

source:
  fn: otlhs-{{ version }}.tar.gz  # [not win]
  url: https://github.com/openturns/otlhs/archive/v{{ version }}.tar.gz  # [not win]
  sha256: 9e1f3282d3210581d9b5f62c3105b384f4e238ad3df899dcfd83b86e48b63e21  # [not win]

  fn: otlhs-{{ version }}-py2.7-i686.exe  # [win32 and py27]
  url: https://github.com/openturns/build/releases/download/v1.8/otlhs-{{ version }}-py2.7-i686.exe  # [win32 and py27]
  sha256: dd06dc0fc160bcdd826f1f1001b49f36cba43d67e22c432e3b7e9fb5b6d0d76b  # [win32 and py27]

  fn: otlhs-{{ version }}-py2.7-x86_64.exe  # [win64 and py27]
  url: https://github.com/openturns/build/releases/download/v1.8/otlhs-{{ version }}-py2.7-x86_64.exe  # [win64 and py27]
  sha256: 2dcc065b6798ef6d01360e12bf7b44e902973425052531816213a512c1a0ffcf  # [win64 and py27]

  fn: otlhs-{{ version }}-py3.4-i686.exe  # [win32 and py34]
  url: https://github.com/openturns/build/releases/download/v1.8/otlhs-{{ version }}-py3.4-i686.exe  # [win32 and py34]
  sha256: d1613e14d593f3ff3762a3a717765df9ac28571e8d2d95d37e779ef9279553ac  # [win32 and py34]

  fn: otlhs-{{ version }}-py3.4-x86_64.exe  # [win64 and py34]
  url: https://github.com/openturns/build/releases/download/v1.8/otlhs-{{ version }}-py3.4-x86_64.exe  # [win64 and py34]
  sha256: baf0ff915be93c091388ae2974f4ab4a8062f0aac7143910af939d054d6af666  # [win64 and py34]

  fn: otlhs-{{ version }}-py3.5-i686.exe  # [win32 and py35]
  url: https://github.com/openturns/build/releases/download/v1.8/otlhs-{{ version }}-py3.5-i686.exe  # [win32 and py35]
  sha256: 4f587422b93d255a83e145ec0c1798ace2ae63defb338ca7a194257b1b2cee35  # [win32 and py35]

  fn: otlhs-{{ version }}-py3.5-x86_64.exe  # [win64 and py35]
  url: https://github.com/openturns/build/releases/download/v1.8/otlhs-{{ version }}-py3.5-x86_64.exe  # [win64 and py35]
  sha256: 8a398b641372b1e3c7c3a971bdc7d0697d5d738e46b5e3346e9840d9b3ca454a  # [win64 and py35]

build:
  number: 1

requirements:
  build:
    - toolchain
    - python
    - cmake  # [not win]
    - swig  # [not win]
    - openturns  # [not win]

  run:
    - python
    - openturns

test:
  imports:
    - otlhs

about:
  home: http://openturns.org/
  license: LGPLv3
  license_file: COPYING.LESSER  # [not win]
  summary: Optimized LHS module

extra:
  recipe-maintainers:
    - jschueller
