travis:
  secure:
    BINSTAR_TOKEN: uJMdGGFLsdvJcteiUWimYe+e74l5WuojaKvd/BGibR3y1/vEVGuhc1tFLhwUFODacRlorB8wxkT/WXzz0tfWMVzR4cPnOHwi7euFXJVAJmIpvnfAxu8xSY9krXHmMjjsChqIwleBv1INZMVMBQvwkA7dvtLTh9Pd0ZrvSMhvGxCm9OfkoIjpZMFVOqw4mJhCMGypNpHoKsy4OcSHUCJZWprhmmzzB/n+/yvinMvVATFZWz2Vq70nQh85/hXeRhw9q81Gakjo/rpn8f50u4cBJvLRmp9yMb+NsBSq5zPZdETtT7g0s1aJBFI158/am6EvD9MjrXedzYX6zUoUbwS01XqrjMxUAOOqs8Q7tJMlkla6Pcx9jo4Wm1gRZ1s44ptigsIKQUBqeciCpROIAE8WvbkBX5UkHVZxW5ym72LOoq5TIIrC0r3l4mW9K4BQpWxXj7W29MYe0BuNQsbfmvaNAaFdqN9oUhRxvv0Pjwz7xKNT9kjYuYILKdz53RQCIfgHmmwnl9ZIUccD0xPf4yyvsF/2Hefs/da1dFv9CxAmz8jLvxqkjIGS3tWb2IKRwFCi4iIoCc0NHg5KZKSQ/QTEC1QeV2szz0BQTQpallWuTBkur6ZBeewFVauQ5avHEI/ylbsiMp36ncgVmNAy8LpwFelcBHup53Mt/G0FjkSeiFc=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
